
name: Expo Preview
on: [
  pull_request
  ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.x

          uses: actions/setup-node@v4
          with:
            node-version: 18.x
              
        - name: Install dependencies
          run: npm ci

        - name: Run tests
          run: npm test 
          
  create_preview:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v3
        
        - name: Use Node.js 18.x
          uses: actions/setup-node@v4
          with:
            node-version: 18.x

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
              packager: npm
              eas-version: latest
              token: ${{ secrets.EXPO_TOKEN }}
              
        - name: Install dependencies
          run: npm install

        - name: 🚀 Create preview
          uses: expo/expo-github-action/preview@v8
          with:
            command: eas update --auto
